version: '2.1'

services:
  mysql:
    build:
      context: ./MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kumparannews
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: kumparan_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    tty: true

  producer:
    build: 
       context: ./Producer
    volumes:
      - "./Producer:/producer"
    container_name: kumparan_producer
    ports:
      - "3002:3002"
    tty: true
    depends_on:
      - rabbit1

  consumer:
    build: 
      context: ./Consumer
    volumes:
      - "./Consumer:/consumer"
    container_name: kumparan_consumer
    ports:
      - "3003:3003"
    tty: true
    depends_on:
      - rabbit1
      - mysql

  
  rabbit1:
    image: "rabbitmq:3-management"
    container_name: kumparan_bus
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    tty: true
    labels:
      NAME: "rabbitmq1"
volumes:
  mysql-data:

  